server:
  port: 8099


spring:
  datasource:
    url: jdbc:mysql://47.104.189.223:3306/shangcg?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Shang123.
    database: shangcg
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 47.104.189.223
    port: 6379
    password: shangcg123
    database: 0
    jedis:
      pool:
        max-active: 50

mybatis:
  type-aliases-package: com.shangcg.mapping
  mapper-locations: classpath*:mapping/*.xml

